name: mantid setup basic workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout mantidSetup
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: mantid-setup
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Test Mantid Import
        run: python -c "from mantid import simpleapi"
