name: mantid setup basic workflow

# Controls when the workflow will run
on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout mantidSetup
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Mantid
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda create -n test-env python=3.8
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate test-env
          conda install -c conda-forge -c mantid/label/nightly mantid
          ulimit -c unlimited
          python -c "
          import sys
          import mantid.simpleapi
          del sys.modules['mantid.simpleapi']
          del sys.modules['mantid']
          del mantid.simpleapi
          del mantid
          "
          sudo chmod -R +rwx /var/crash/*



      - uses: actions/upload-artifact@master # capture all crashes as build artifacts
        with:
          name: crashes
          path: /var/crash